%==========================================================================
% The sequence of triangle numbers is generated by adding the natural
% numbers. So the 7th triangle number would be
%                   1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
% The first ten terms would be:
%                   1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
% Let us list the factors of the first seven triangle numbers:
%
%      1: 1
%      3: 1,3
%      6: 1,2,3,6
%     10: 1,2,5,10
%     15: 1,3,5,15
%     21: 1,3,7,21
%     28: 1,2,4,7,14,28
%
% We can see that 28 is the first triangle number to have over five
% divisors.
%
% What is the value of the first triangle number to have over five hundred
% divisors?
%==========================================================================
clear; close all;
%--------------------------------------------------------------------------
number = 1;
while number >= 1
    triangle_numbers = cumsum(1:number);
    triangle_number = triangle_numbers(end);
    %------------------------------------------------------------------
    prime_factors = factor(triangle_number); % gets all prime factors
    divisors = [1,prime_factors(1)];
    for idx = prime_factors(2:end)
        divisors = [1;idx]*divisors;
        divisors = unique(divisors(:)');
    end
    % disp([num2str(triangle_number),' has ',num2str(length(divisors)),' factors'])
    if length(divisors) > 500
        %------------------------------------------------------------------
        fprintf('The answer is: %d\n',triangle_number)
        %------------------------------------------------------------------
        return;
    end
    number = number + 1;
end
